use_frameworks!

platform :ios, '10.0'

target 'WDWaterfallCollectionLayout_Example' do
  pod 'WDWaterfallCollectionLayout', :path => '../'

  target 'WDWaterfallCollectionLayout_Tests' do
    inherit! :search_paths

    
  end
end
